### PR TITLE
Version 0.1.1

### PR DESCRIPTION
**Pull request by XedinUnknown**
Bugfixes.

### CODE REVIEW

**Comment by XedinUnknown** [comment]
Many files that are not necessary for the lib to work should now be excluded from the dist archive. Try this command to test:
```bash
git archive --format=tar HEAD | gzip >./build/0.1.1.tar.gz
```

**Review by mecha — COMMENTED** [review]
Tested the `git archive` process and confirmed that the files listed as `export-ignore` are excluded from the archive.

**Review by mecha — APPROVED** [review]
A approve, now that issue #9 has been fixed by PR #10.

**Comment by XedinUnknown** [comment]
@mecha, do you agree with what I've excluded from archive?

**Comment by mecha** [comment]
@XedinUnknown Yes - it looks like only the bare minimum required for the lib to work is included. Maybe `.gitattributes` is extra; don't know. But it looks good to me in its current state.

**Comment by XedinUnknown** [comment]
Merging this as soon as PR build ready

**Pull request merged**
